export default {
    DOCUMENT_AI_PROVIDER: 'GOOGLE_DOCUMENT_AI_PROVIDER',
    APPLICATION_CREDENTIALS: 'GOOGLE_APPLICATION_CREDENTIALS',
    PROJECT_ID: 'PROJECT_ID',
    LOCATION: 'LOCATION',
    PROCESSOR_ID: 'PROCESSOR_ID'

}