export const DOCUMENT_AI_CONFIG = {
    DOCUMENT_AI_PROVIDER: 'GOOGLE_DOCUMENT_AI_PROVIDER',
    APPLICATION_CREDENTIALS: 'GOOGLE_APPLICATION_CREDENTIALS',
    PROJECT_ID: 'PROJECT_ID',
    LOCATION: 'LOCATION',
    PROCESSOR_ID: 'PROCESSOR_ID'
} as const;